import React from 'react'
import Container from './Container'
import Sidebar from './Sidebar'
import Head from 'next/head'

const DashBoardLayout = ({children}) => {
  return (
    <div>
      <Head>
        <title>UK Care Connection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ukc-favicon-white.png" />
      </Head>
      <div className='flex h-screen bg-slate-200 relative'>
        <Sidebar />
        <Container>
          {children}
        </Container>
      </div>
    </div>
  )
}

export default DashBoardLayout