import Head from 'next/head'
import DashBoardLayout from '@/components/DashBoard'
import Sidebar from '@/components/DashBoard/Sidebar'

export default function Home() {
  return (
    <>
      <Head>
        <title>UK Care Connection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ukc-favicon-white.png" />
      </Head>
      <DashBoardLayout />
    </>
  )
}
